"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

fib_sum = 2

fib_current = 2
fib_old = 1


while fib_current <= 4000000:

    i = fib_current
    fib_current = fib_current + fib_old
    fib_old = i

    if fib_current % 2 == 0:
        fib_sum = fib_sum + fib_current


print fib_sum
